name: Android CI

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Elixir
      run: |
        wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
        brew install erlang
        mkdir $HOME/elixir && cd $HOME/elixir
        wget https://github.com/elixir-lang/elixir/releases/download/v1.11.4/Precompiled.zip
        unzip Precompiled.zip
        echo "$HOME/elixir/bin" >> $GITHUB_PATH

    - name: Set up hex & rebar
      run: |
        mix local.hex --force
        mix local.rebar --force

    - name: Build with XCode
      run: xcodebuild
      
    # - name: Upload APK
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: app
    #     path: app/build/outputs/apk/debug/app-debug.apk